# Generated by Django 5.2.4 on 2025-07-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0002_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='fecha_fin',
        ),
        migrations.AddField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion_semanas',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
